books/urls.py
from django.urls import path, include
from . import views

app_name = 'books'

urlpatterns = [
    path('save/<str:isbn>/', views.save_book, name='save_book'),
    path('delete/<str:isbn>/', views.delete_book, name='delete_book'),
    path('user/bookshelf/', views.bookshelf, name='bookshelf'),
]

mylibrary/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls')),
    path('account/', include('account.urls')),
    path('books/', include('books.urls')),
    path('social-auth/', include('social_django.urls', namespace='social')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.home_page, name="home_page"),
    path('dashboard/', views.dashboard, name="dashboard"),
    path('search/', views.search, name='search_results'),
    path('like/', views.post_like, name='like'),
    path('post/<slug:slug>/', views.post_detail, name='post_detail'),
    path('book/<str:isbn>/', views.book_detail, name='book_detail'),
    #  user activities panel
    path('user/posts/', views.user_posts, name='user_posts'),
    path('user/comments/', views.user_comments, name='user_comments'),
    path('user/follows/', views.user_follows, name='user_follows'),
    path('user/likes/', views.user_likes, name='user_likes'),
    #  deleting content
    path('comment/delete/<int:comment_id>/', views.comment_delete, name='delete_comment'),
    path('post/delete/<int:post_id>/', views.post_delete, name='delete_post'),
]

posts/models.py
from django.db import models
from django.conf import settings
from django.utils.text import slugify


class Post(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             related_name='posts',
                             on_delete=models.CASCADE)
    text = models.CharField(max_length=350)
    slug = models.SlugField(max_length=200,
                            blank=True,
                            unique=True)
    created = models.DateField(auto_now_add=True,
                               db_index=True)
    users_like = models.ManyToManyField(settings.AUTH_USER_MODEL,
                                        related_name='posts_liked',
                                        blank=True)

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        if not self.slug:
            self.slug = slugify(self.user) + "-" + str(self.id)
            self.save()


class Comment(models.Model):
    post = models.ForeignKey(Post,
                             on_delete=models.CASCADE,
                             related_name='comments')
    author = models.ForeignKey(settings.AUTH_USER_MODEL,
                               on_delete=models.CASCADE)
    text = models.CharField(max_length=200)
    created = models.DateField(auto_now_add=True,
                               db_index=True)

    class Meta:
        ordering = ['-created']

posts/forms.py
from django import forms
from .models import Post, Comment


class PostCreateForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['text']
        widgets = {'text': forms.Textarea(attrs={'placeholder': 'Enter text'})}


class CommentCreateForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text']

posts/views.py
from django.shortcuts import render, redirect, get_object_or_404, HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from .models import Post, Comment
from .forms import PostCreateForm, CommentCreateForm
from django.contrib.auth.models import User
from django.http import JsonResponse
import json
import requests
from django.core.paginator import Paginator
from books.models import Book


def home_page(request):
    if request.user.is_authenticated:
        return redirect('posts:dashboard')
    else:
        return render(request, 'home_page.html')


@login_required
def dashboard(request):
    following_ids = request.user.following.values_list('id', flat=True)
    post_objects = Post.objects.order_by('-created')
    posts = []

    # add matching 'Post' objects to list 'posts'
    if following_ids:
        for post in list(post_objects):
            if post in Post.objects.filter(user_id__in=following_ids):
                posts.append(post)

    # pagination
    paginated_posts = Paginator(posts, 8)
    page_number = request.GET.get('page')
    page_obj = paginated_posts.get_page(page_number)

    # handling creating post form
    if request.method == 'POST':
        form = PostCreateForm(request.POST)
        if form.is_valid():
            new_post = form.save(commit=False)
            new_post.user = request.user
            new_post.save()
            return redirect('posts:dashboard')
    else:
        form = PostCreateForm()

        return render(request, 'posts/dashboard.html', {'paginated_posts': paginated_posts,
                                                        'page_obj': page_obj,
                                                        'form': form})


@login_required
def search(request):
    query = request.GET.get('search')

    # search for users
    if request.method == 'GET':
        search_list = User.objects.filter(username__contains=query).exclude(id=request.user.id)

    # cleaning the query for api request
    cleaned = query.partition('/')
    query = cleaned[0]
    page = cleaned[2]
    if page == '':
        page = 0
    page = int(page) + 1
    query = query + '/' + str(page)

    if request.method == 'GET':
        # search for books using itbook.store api
        books_list = []
        response = requests.get(f'https://api.itbook.store/1.0/search/{query}')
        response_json = response.json()

        if response.status_code == 200:
            for book in response_json['books']:
                books_list.append(book)

        elif response.status_code == 404:
            books_list = []

        return render(request, 'posts/search_results.html', {'search_list': search_list,
                                                             'books_list': books_list,
                                                             'query': query,
                                                             'response_json': response_json
                                                             })


@login_required
def post_like(request):
    is_ajax = request.headers.get('X-Requested-With') == 'XMLHttpRequest'
    if is_ajax:
        if request.method == 'POST':
            data = json.load(request)
            post_id = data.get('id')
            action = data.get('action')
            post = Post.objects.get(id=post_id)
            if action == 'like':
                post.users_like.add(request.user)
                return JsonResponse({'status': 'liked'})
            else:
                post.users_like.remove(request.user)
                return JsonResponse({'status': 'unliked'})
        return JsonResponse({'status': 'error-1'})
    else:
        return JsonResponse({'status': 'error-2'})


@login_required
def post_detail(request, slug):
    post = get_object_or_404(Post, slug=slug)

    if request.method == 'POST':
        comment_form = CommentCreateForm(request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.author = request.user
            new_comment.post = post
            new_comment.save()
            return redirect('posts:post_detail', slug)
    else:
        comment_form = CommentCreateForm()
        return render(request, 'posts/post_detail.html', {'post': post,
                                                          'comment_form': comment_form})


@login_required
def comment_delete(request, comment_id):
    comment = get_object_or_404(Comment, id=comment_id)
    if request.user == comment.author:
        comment.delete()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))


@login_required
def post_delete(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    if request.user == post.user:
        post.delete()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))


@login_required
def user_posts(request):
    posts = Post.objects.filter(user=request.user).order_by('-created')
    return render(request, 'posts/user_posts.html', {'posts': posts})


@login_required
def user_comments(request):
    comments = Comment.objects.filter(author=request.user)
    return render(request, 'posts/user_comments.html', {'comments': comments})


@login_required
def user_follows(request):
    follows = request.user.following.all()
    return render(request, 'posts/user_follows.html', {'follows': follows})


@login_required
def user_likes(request):
    posts = request.user.posts_liked.all()
    return render(request, 'posts/user_likes.html', {'posts': posts})


@login_required
def book_detail(request, isbn):
    user_books = Book.objects.filter(user=request.user)
    isbn_list = []
    for book in user_books:
        isbn_list.append(book.isbn)

    # get detail of book
    response = requests.get(f'https://api.itbook.store/1.0/books/{isbn}')
    response_json = response.json()

    if response.status_code == 200:
        book = response_json

    elif response.status_code == 404:
        book = 'No book found!'

    return render(request, 'posts/book_detail.html', {'book': book,
                                                      'isbn_list': isbn_list})

posts/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;700&display=swap" rel="stylesheet">
    <script src="https://kit.fontawesome.com/49b5438e0f.js" crossorigin="anonymous"></script>
    <link href="{% static 'css/base.css' %}" rel="stylesheet">
    {% block extra_css %}
    {% endblock %}
</head>
<body>
<div class="container">
    <div class="navigation">
        <ul>
            <li class="list">
                <a>
                    <span class="icon"><i class="fas fa-book"></i></span>
                    <span class="title" style="font-weight: bold">MyLibrary</span>
                </a>
            </li>
            <li class="list">
                <a href="{% url 'posts:dashboard' %}" class="home-link">
                    <span class="icon"><i class="fas fa-home"></i></span>
                    <span class="title">Home</span>
                </a>
            </li>
            <li class="list">
                <a href="{% url 'books:bookshelf' %}">
                    <span class="icon"><i class="fas fa-book"></i></span>
                    <span class="title">My books</span>
                </a>
            </li>
            <li class="list">
                <a href="{% url 'posts:user_posts' %}">
                    <span class="icon"><i class="far fa-comment-alt"></i></span>
                    <span class="title">My activities</span>
                </a>
            </li>
            <li class="list">
                <a href="{% url 'edit' %}">
                    <span class="icon"><i class="fas fa-user-edit"></i></span>
                    <span class="title">Profile</span>
                </a>
            </li>
            <li class="list">
                <a href="{% url 'logout' %}">
                    <span class="icon"><i class="fas fa-sign-out-alt"></i></span>
                    <span class="title">Log out</span>
                </a>
            </li>
        </ul>
    </div>

    <div class="main">
        <div class="topbar">
            <div class="toggle">
                <i class="fas fa-bars open"></i>
            </div>
            <div class="home-title">
                <h2>{% block text %}Home{% endblock %}</h2>
            </div>
            {# search #}
            <div class="search">
                <form action="{% url 'posts:search_results' %}" method="GET">
                    <label>
                        <input type="text" placeholder="Search..." name="search" pattern="^[A-Za-z0-9 _]*[A-Za-z0-9][A-Za-z0-9 _]*$"
                               title="Sorry, no special characters are allowed">
                        <i class="fas fa-search"></i>
                    </label>
                </form>
            </div>
        </div>

    {% block content %}

    {% endblock %}
    </div>
</div>

</body>

<script>

    let menuToggle = document.querySelector('.toggle');
    let navigation = document.querySelector('.navigation')
    let main = document.querySelector('.main')

    menuToggle.onclick = function(){
        menuToggle.classList.toggle('active');
        main.classList.toggle('active');
        navigation.classList.toggle('active');
    }

    
    let links = document.querySelectorAll('li a')
    let currentLocation = window.location.href
    let homeLink = document.querySelector('.home-link')

    for (let i= 0; i<links.length; i++){
        if (links[i].href === currentLocation){
            links[i].closest('li').classList.add('active')
        } else if (currentLocation.indexOf(`${homeLink.href}?page`) !== -1){
            homeLink.closest('li').classList.add('active')
        }
    }

</script>

{% block extra_js %}
{% endblock %}

</html>

posts/templates/home_page.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Home page</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;700&display=swap" rel="stylesheet">
    <script src="https://kit.fontawesome.com/49b5438e0f.js" crossorigin="anonymous"></script>
    <link href="{% static 'css/home_page.css' %}" rel="stylesheet">

</head>
<body>

<div class="wrapper">
    <div class="site-info">
        <h2>Welcome to &nbsp;&nbsp;<i class="fas fa-book"></i> ITLibrary</h2>
        <h4>A website, where you can discover new IT books and share your thoughts with other specialists</h4>
    </div>
    <div class="login-info">
        <p>To start using the site, <a href="{% url 'register' %}">register here</a></p>
        <p>Or <a href="{% url "social:begin" "google-oauth2" %}">sign-in with google</a></p>
        <p>If you already have an account, <a href="{% url 'login' %}">log in here</a></p>
    </div>
</div>

</body>
</html>