books/urls.py
from django.urls import path, include
from . import views

app_name = 'books'

urlpatterns = [
    path('save/<str:isbn>/', views.save_book, name='save_book'),
    path('delete/<str:isbn>/', views.delete_book, name='delete_book'),
    path('user/bookshelf/', views.bookshelf, name='bookshelf'),
]

mylibrary/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls')),
    path('account/', include('account.urls')),
    path('books/', include('books.urls')),
    path('social-auth/', include('social_django.urls', namespace='social')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.home_page, name="home_page"),
    path('dashboard/', views.dashboard, name="dashboard"),
    path('search/', views.search, name='search_results'),
    path('like/', views.post_like, name='like'),
    path('post/<slug:slug>/', views.post_detail, name='post_detail'),
    path('book/<str:isbn>/', views.book_detail, name='book_detail'),
    #  user activities panel
    path('user/posts/', views.user_posts, name='user_posts'),
    path('user/comments/', views.user_comments, name='user_comments'),
    path('user/follows/', views.user_follows, name='user_follows'),
    path('user/likes/', views.user_likes, name='user_likes'),
    #  deleting content
    path('comment/delete/<int:comment_id>/', views.comment_delete, name='delete_comment'),
    path('post/delete/<int:post_id>/', views.post_delete, name='delete_post'),
]

books/models.py
from django.db import models
from django.conf import settings


class Book(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE,
                             related_name='books')
    isbn = models.CharField(max_length=100)

books/views.py
from django.shortcuts import render, redirect
from .models import Book
from django.contrib.auth.decorators import login_required
import requests


@login_required
def bookshelf(request):
    user = request.user
    user_books = Book.objects.filter(user=user)
    books = []
    for book in user_books:
        response = requests.get(f'https://api.itbook.store/1.0/books/{book.isbn}')
        single_book = response.json()
        books.append(single_book)
    return render(request, 'books/bookshelf.html', {'books': books})


@login_required
def save_book(request, isbn):

    # get isbn values of books of user
    user_books = Book.objects.filter(user=request.user)
    books = []
    for book in user_books:
        books.append(book.isbn)

    # check if book with given isbn doesn't already exist in user's collection
    if isbn not in books:
        # create new book object
        book = Book(user=request.user, isbn=isbn)
        book.save()
    return redirect('books:bookshelf')


@login_required
def delete_book(request, isbn):
    user_books = Book.objects.filter(user=request.user)
    for book in user_books:
        if book.isbn == isbn:
            book.delete()
    return redirect('books:bookshelf')

books/templates/books/bookshelf.html
{% extends 'base.html' %}
{% load static %}

{% block extra_css %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/user_activity.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/dashboard.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/search_results.css' %}">
{% endblock %}

{% block content %}

    <div class="books-list">
        {% for book in books %}
            <a href="{% url 'posts:book_detail' book.isbn13 %}" class="book-card">
                <div class="book-link">
                    <p>{{ book.title }}</p>
                    <img src="{{ book.image }}">
                    <p>Click for details</p>
                </div>
            </a>
        {% empty %}
            <p>Sorry, looks like there are no results</p>
        {% endfor %}
    </div>

{% endblock %}