books/urls.py
from django.urls import path, include
from . import views

app_name = 'books'

urlpatterns = [
    path('save/<str:isbn>/', views.save_book, name='save_book'),
    path('delete/<str:isbn>/', views.delete_book, name='delete_book'),
    path('user/bookshelf/', views.bookshelf, name='bookshelf'),
]

mylibrary/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls')),
    path('account/', include('account.urls')),
    path('books/', include('books.urls')),
    path('social-auth/', include('social_django.urls', namespace='social')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.home_page, name="home_page"),
    path('dashboard/', views.dashboard, name="dashboard"),
    path('search/', views.search, name='search_results'),
    path('like/', views.post_like, name='like'),
    path('post/<slug:slug>/', views.post_detail, name='post_detail'),
    path('book/<str:isbn>/', views.book_detail, name='book_detail'),
    #  user activities panel
    path('user/posts/', views.user_posts, name='user_posts'),
    path('user/comments/', views.user_comments, name='user_comments'),
    path('user/follows/', views.user_follows, name='user_follows'),
    path('user/likes/', views.user_likes, name='user_likes'),
    #  deleting content
    path('comment/delete/<int:comment_id>/', views.comment_delete, name='delete_comment'),
    path('post/delete/<int:post_id>/', views.post_delete, name='delete_post'),
]

posts/models.py
from django.db import models
from django.conf import settings
from django.utils.text import slugify


class Post(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             related_name='posts',
                             on_delete=models.CASCADE)
    text = models.CharField(max_length=350)
    slug = models.SlugField(max_length=200,
                            blank=True,
                            unique=True)
    created = models.DateField(auto_now_add=True,
                               db_index=True)
    users_like = models.ManyToManyField(settings.AUTH_USER_MODEL,
                                        related_name='posts_liked',
                                        blank=True)

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        if not self.slug:
            self.slug = slugify(self.user) + "-" + str(self.id)
            self.save()


class Comment(models.Model):
    post = models.ForeignKey(Post,
                             on_delete=models.CASCADE,
                             related_name='comments')
    author = models.ForeignKey(settings.AUTH_USER_MODEL,
                               on_delete=models.CASCADE)
    text = models.CharField(max_length=200)
    created = models.DateField(auto_now_add=True,
                               db_index=True)

    class Meta:
        ordering = ['-created']

posts/forms.py
from django import forms
from .models import Post, Comment


class PostCreateForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['text']
        widgets = {'text': forms.Textarea(attrs={'placeholder': 'Enter text'})}


class CommentCreateForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text']

posts/views.py
from django.shortcuts import render, redirect, get_object_or_404, HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from .models import Post, Comment
from .forms import PostCreateForm, CommentCreateForm
from django.contrib.auth.models import User
from django.http import JsonResponse
import json
import requests
from django.core.paginator import Paginator
from books.models import Book


def home_page(request):
    if request.user.is_authenticated:
        return redirect('posts:dashboard')
    else:
        return render(request, 'home_page.html')


@login_required
def dashboard(request):
    following_ids = request.user.following.values_list('id', flat=True)
    post_objects = Post.objects.order_by('-created')
    posts = []

    # add matching 'Post' objects to list 'posts'
    if following_ids:
        for post in list(post_objects):
            if post in Post.objects.filter(user_id__in=following_ids):
                posts.append(post)

    # pagination
    paginated_posts = Paginator(posts, 8)
    page_number = request.GET.get('page')
    page_obj = paginated_posts.get_page(page_number)

    # handling creating post form
    if request.method == 'POST':
        form = PostCreateForm(request.POST)
        if form.is_valid():
            new_post = form.save(commit=False)
            new_post.user = request.user
            new_post.save()
            return redirect('posts:dashboard')
    else:
        form = PostCreateForm()

        return render(request, 'posts/dashboard.html', {'paginated_posts': paginated_posts,
                                                        'page_obj': page_obj,
                                                        'form': form})


@login_required
def search(request):
    query = request.GET.get('search')

    # search for users
    if request.method == 'GET':
        search_list = User.objects.filter(username__contains=query).exclude(id=request.user.id)

    # cleaning the query for api request
    cleaned = query.partition('/')
    query = cleaned[0]
    page = cleaned[2]
    if page == '':
        page = 0
    page = int(page) + 1
    query = query + '/' + str(page)

    if request.method == 'GET':
        # search for books using itbook.store api
        books_list = []
        response = requests.get(f'https://api.itbook.store/1.0/search/{query}')
        response_json = response.json()

        if response.status_code == 200:
            for book in response_json['books']:
                books_list.append(book)

        elif response.status_code == 404:
            books_list = []

        return render(request, 'posts/search_results.html', {'search_list': search_list,
                                                             'books_list': books_list,
                                                             'query': query,
                                                             'response_json': response_json
                                                             })


@login_required
def post_like(request):
    is_ajax = request.headers.get('X-Requested-With') == 'XMLHttpRequest'
    if is_ajax:
        if request.method == 'POST':
            data = json.load(request)
            post_id = data.get('id')
            action = data.get('action')
            post = Post.objects.get(id=post_id)
            if action == 'like':
                post.users_like.add(request.user)
                return JsonResponse({'status': 'liked'})
            else:
                post.users_like.remove(request.user)
                return JsonResponse({'status': 'unliked'})
        return JsonResponse({'status': 'error-1'})
    else:
        return JsonResponse({'status': 'error-2'})


@login_required
def post_detail(request, slug):
    post = get_object_or_404(Post, slug=slug)

    if request.method == 'POST':
        comment_form = CommentCreateForm(request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.author = request.user
            new_comment.post = post
            new_comment.save()
            return redirect('posts:post_detail', slug)
    else:
        comment_form = CommentCreateForm()
        return render(request, 'posts/post_detail.html', {'post': post,
                                                          'comment_form': comment_form})


@login_required
def comment_delete(request, comment_id):
    comment = get_object_or_404(Comment, id=comment_id)
    if request.user == comment.author:
        comment.delete()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))


@login_required
def post_delete(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    if request.user == post.user:
        post.delete()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))


@login_required
def user_posts(request):
    posts = Post.objects.filter(user=request.user).order_by('-created')
    return render(request, 'posts/user_posts.html', {'posts': posts})


@login_required
def user_comments(request):
    comments = Comment.objects.filter(author=request.user)
    return render(request, 'posts/user_comments.html', {'comments': comments})


@login_required
def user_follows(request):
    follows = request.user.following.all()
    return render(request, 'posts/user_follows.html', {'follows': follows})


@login_required
def user_likes(request):
    posts = request.user.posts_liked.all()
    return render(request, 'posts/user_likes.html', {'posts': posts})


@login_required
def book_detail(request, isbn):
    user_books = Book.objects.filter(user=request.user)
    isbn_list = []
    for book in user_books:
        isbn_list.append(book.isbn)

    # get detail of book
    response = requests.get(f'https://api.itbook.store/1.0/books/{isbn}')
    response_json = response.json()

    if response.status_code == 200:
        book = response_json

    elif response.status_code == 404:
        book = 'No book found!'

    return render(request, 'posts/book_detail.html', {'book': book,
                                                      'isbn_list': isbn_list})

posts/templates/posts/book_detail.html
{% extends 'base.html' %}
{% load static %}

{% block extra_css %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/book_detail.css' %}">
{% endblock %}

{% block content %}

<div class="book">
    <div class="book-image">
        <img src="{{ book.image }}">
    </div>
    <div class="top-info">
        <p>Title: {{ book.title }}</p>
        <p>Subtitle: {{ book.subtitle }}</p>
        <p>Authors: {{ book.authors }}</p>
        <p>Year: {{ book.year }}</p>
        {% if book.isbn13 not in isbn_list %}
            <a href="{% url 'books:save_book' book.isbn13 %}">Save book</a>
        {% else %}
            <a href="{% url 'books:delete_book' book.isbn13 %}">Remove book from collection</a>
        {% endif %}
    </div>
    <div class="additional-info">
        <p>Description: {{ book.desc }}</p>
        <p>Pages: {{ book.pages }}</p>
        <p>Publisher: {{ book.publisher }}</p>
        <p>See book in itbook.store: <a href="{{ book.url }}">Link</a></p>
        <p>isbn10: {{ book.isbn10 }}</p>
        <p>isbn13: {{ book.isbn13 }}</p>
        <p>{{ book.pdf }}</p>
    </div>
</div>

{% endblock %}

posts/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load static %}


{% block extra_css %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/post_detail.css' %}">

{% endblock %}

{% block content %}
<div class="post-div">
    <div class="post-card">
        <a href="{{ post.user.get_absolute_url }}" class="profile-link">
            <div class="link">
                <div class="profile-picture">
                    <img src="{{ post.user.profile.profile_picture.url }}">
                </div>
                <span>{{ post.user }}</span>
            </div>
        </a>
        <p class="text">{{ post.text }}</p>
        <div class="under-text">
                        <span>
                            <a href="#" data-id="{{ post.id }}"
                                data-action="{% if post in request.user.posts_liked.all %}un{% endif %}like"
                                class="like button">

                                <i class="far fa-heart {% if request.user in post.users_like.all %}liked{% endif %}"></i>

                                <span class="count-total">{{ post.users_like.all.count }}</span>
                            </a>
                        </span>
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            <a href="{% url 'posts:post_detail' post.slug %}" class="comment">
                <span><i class="far fa-comment"></i></span>
                <span class="count-total">{{ post.comments.all.count }}</span>
            </a>
        </div>
    </div>
</div>

<div class="create-comment">
    <i class="far fa-comment"></i>
    <form method="POST">
        {% csrf_token %}
        {{ comment_form.as_p }}
        <input type="submit" value="submit">
    </form>
</div>

<div class="comments">
    {% for comment in post.comments.all %}
        <div class="comment">
            <div class="topbar">
                <a href="{{ comment.author.get_absolute_url }}" class="comment-link">
                    <div class="link">
                        <div class="profile-picture">
                            <img src="{{ comment.author.profile.profile_picture.url }}">
                        </div>
                        <span>{{ comment.author }}</span>
                    </div>
                </a>
                {% if request.user == comment.author %}
                    <span class="delete-comment">
                        <a href="#" onClick="document.getElementById('delete-form-{{ comment.id }}').submit()">
                            <i class="far fa-trash-alt"></i>
                            <form method="post" action="{% url 'posts:delete_comment' comment.id %}" id="delete-form-{{ comment.id }}">
                                {% csrf_token %}
                                <input type="hidden">
                            </form>
                        </a>
                    </span>
                {% endif %}
            </div>
            <p>{{ comment.text }}</p>
        </div>
    {% endfor %}
</div>

{% endblock %}

{% block extra_js %}
    <script src="https://cdn.jsdelivr.net/npm/js-cookie@2.2.1/src/js.cookie.min.js"></script>
    <script>

        let likeButton = document.querySelector('.like')
        let likeIcon = document.querySelector('.fa-heart')
        let totalLikes = document.querySelector('.count-total')

        likeButton.addEventListener('click', function sendPost(){
            fetch({% url "posts:like" %}, {
                method: "POST"
                credentials: "same-origin",
                headers: {
                    "X-Requested-With": "XMLHttpRequest",
                    "X-CSRFToken": Cookies.get('csrftoken'),
                },
                body: JSON.stringify({id: this.dataset.id, action: this.dataset.action })
            })
            .then(response => response.json())
            .then(data => {
                likeIcon.classList.toggle('liked')

                if(String(data['status']) === 'liked'){
                    totalLikes.textContent = parseInt(totalLikes.textContent) + 1
                    if (this.dataset.action === 'like'){
                        this.dataset.action = 'unlike'
                    }
                } else{
                    totalLikes.textContent = parseInt(totalLikes.textContent) - 1
                    if (this.dataset.action === 'unlike'){
                        this.dataset.action = 'like'
                    }
                }
            })
        })


    </script>
{% endblock %}

posts/templates/posts/user_comments.html
{% extends 'base.html' %}
{% load static %}

{% block extra_css %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/user_activity.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/dashboard.css' %}">
{% endblock %}
{% block text %}
    Created comments
{% endblock %}
{% block content %}
    <div class="user-links">
        <a href="{% url 'posts:user_posts' %}">
            <div class="user-link">
                Posts
                <i class="far fa-clipboard"></i>
            </div>
        </a>
        <a href="{% url 'posts:user_comments' %}">
            <div class="user-link">
                Comments
                <i class="far fa-comment"></i>
            </div>
        </a>
        <a href="{% url 'posts:user_likes' %}">
            <div class="user-link">
                Likes
                <i class="far fa-heart"></i>
            </div>
        </a>
        <a href="{% url 'posts:user_follows' %}">
            <div class="user-link">
                Follows
                <i class="fas fa-user-friends"></i>
            </div>
        </a>
    </div>

    <div class="comments">
    {% for comment in comments %}
        <div class="comment">
            <div class="topbar">
                <a href="{{ comment.author.get_absolute_url }}" class="comment-link">
                    <div class="link">
                        <div class="profile-picture">
                            <img src="{{ comment.author.profile.profile_picture.url }}">
                        </div>
                        <span>{{ comment.author }}</span>
                    </div>
                </a>
                {% if request.user == comment.author %}
                    <span class="delete-comment">
                        <a href="#" onClick="document.getElementById('delete-form-{{ comment.id }}').submit()">
                            <i class="far fa-trash-alt"></i>
                            <form method="post" action="{% url 'posts:delete_comment' comment.id %}" id="delete-form-{{ comment.id }}">
                                {% csrf_token %}
                                <input type="hidden">
                            </form>
                        </a>
                    </span>
                {% endif %}
            </div>
            <p>{{ comment.text }}</p>
        </div>
    {% endfor %}
</div>

{% endblock %}

posts/templates/posts/user_follows.html
{% extends 'base.html' %}
{% load static %}

{% block extra_css %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/user_activity.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/dashboard.css' %}">
{% endblock %}
{% block text %}
    Followed users
{% endblock %}
{% block content %}
    <div class="user-links">
        <a href="{% url 'posts:user_posts' %}">
            <div class="user-link">
                Posts
                <i class="far fa-clipboard"></i>
            </div>
        </a>
        <a href="{% url 'posts:user_comments' %}">
            <div class="user-link">
                Comments
                <i class="far fa-comment"></i>
            </div>
        </a>
        <a href="{% url 'posts:user_likes' %}">
            <div class="user-link">
                Likes
                <i class="far fa-heart"></i>
            </div>
        </a>
        <a href="{% url 'posts:user_follows' %}">
            <div class="user-link">
                Follows
                <i class="fas fa-user-friends"></i>
            </div>
        </a>
    </div>


    <div class="follows-list">
        {% for follower in follows %}
            <div class="follower-card">
                <a href="{{ follower.get_absolute_url }}">
                    <div class="info">
                        <div class="follower-profile-picture">
                            <img src="{{ follower.profile.profile_picture.url }}">
                        </div>
                        {{ follower.username }}
                    </div>
                </a>
                <span class="follow-toggle">
                    <a href="#" data-id="{{ follower.id }}" data-action="{% if request.user in follower.followers.all %}un{% endif %}follow" class="follow-{{ follower.id }} button">
                        {% if request.user not in follower.followers.all %}
                            Follow
                        {% else %}
                            Unfollow
                        {% endif %}
                    </a>
                </span>
            </div>
        {% endfor %}
    </div>
{% endblock %}

{% block extra_js %}
<script src="https://cdn.jsdelivr.net/npm/js-cookie@2.2.1/src/js.cookie.min.js"></script>
<script>

  {% for follower in follows %}

      document.querySelector('.follow-{{ follower.id }}').addEventListener('click', function sendPost(){
        fetch('{% url 'user_follow' %}', {
            method: 'POST',
            credentials: 'same-origin',
            headers: {
                "X-Requested-With": "XMLHttpRequest",
                "X-CSRFToken": Cookies.get('csrftoken'),
            },
            body: JSON.stringify({id: this.dataset.id, action: this.dataset.action })
        })
        .then(response => response.json())
        .then(data => {
            if (String(data['status']) === 'followed') {
                this.textContent = 'Unfollow'
                if (this.dataset.action === 'follow') {
                    this.dataset.action = 'unfollow'
                }
            } else{
                this.textContent = 'Follow'
                if (this.dataset.action === 'unfollow') {
                    this.dataset.action = 'follow'
                }
            }
        })
    })


  {% endfor %}

</script>
{% endblock %}

posts/templates/posts/user_likes.html
{% extends 'base.html' %}
{% load static %}

{% block extra_css %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/user_activity.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/dashboard.css' %}">
{% endblock %}
{% block text %}
    Liked posts
{% endblock %}
{% block content %}
    <div class="user-links">
        <a href="{% url 'posts:user_posts' %}">
            <div class="user-link">
                Posts
                <i class="far fa-clipboard"></i>
            </div>
        </a>
        <a href="{% url 'posts:user_comments' %}">
            <div class="user-link">
                Comments
                <i class="far fa-comment"></i>
            </div>
        </a>
        <a href="{% url 'posts:user_likes' %}">
            <div class="user-link">
                Likes
                <i class="far fa-heart"></i>
            </div>
        </a>
        <a href="{% url 'posts:user_follows' %}">
            <div class="user-link">
                Follows
                <i class="fas fa-user-friends"></i>
            </div>
        </a>
    </div>

    <div class="post-list">
        {% for post in posts %}
            <div class="post-card">
                <a href="{{ post.user.get_absolute_url }}" class="profile-link">
                    <div class="link">
                        <div class="profile-picture">
                            <img src="{{ post.user.profile.profile_picture.url }}">
                        </div>
                        <span>{{ post.user }}</span>
                    </div>
                </a>
                <p class="text">{{ post.text }}</p>
                <div class="under-text">
                     <span>
                            <a  data-id="{{ post.id }}"
                                data-action="{% if post in request.user.posts_liked.all %}un{% endif %}like"
                                class="like button" id="like-button-{{ post.id }}">

                                <i class="far fa-heart {% if request.user in post.users_like.all %}liked{% endif %}"
                                   id="like-icon-{{ post.id }}"></i>

                                <span class="count-total" id="like-count-{{ post.id }}">{{ post.users_like.all.count }}</span>
                            </a>
                        </span>
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    <a href="{% url 'posts:post_detail' post.slug %}" class="comment">
                        <span><i class="far fa-comment"></i></span>
                        <span class="count-total">{{ post.comments.all.count }}</span>
                    </a>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

{% block extra_js %}
    <script src="https://cdn.jsdelivr.net/npm/js-cookie@2.2.1/src/js.cookie.min.js"></script>
    <script>


        {% for post in posts %}

        document.querySelector('#like-button-{{ post.id }}').addEventListener('click', function sendPost(){
            let likeIcon = document.querySelector('#like-icon-{{ post.id }}')
            let totalLikes = document.querySelector('#like-count-{{ post.id }}')
            fetch({% url "posts:like" %}, {
                method: "POST",
                credentials: "same-origin",
                headers: {
                    "X-Requested-With": "XMLHttpRequest",
                    "X-CSRFToken": Cookies.get('csrftoken'),
                },
                body: JSON.stringify({id: this.dataset.id, action: this.dataset.action })
            })
            .then(response => response.json())
            .then(data => {
                likeIcon.classList.toggle('liked')

                if(String(data['status']) === 'liked'){
                    totalLikes.textContent = parseInt(totalLikes.textContent) + 1
                    if (this.dataset.action === 'like'){
                        this.dataset.action = 'unlike'
                    }
                } else{
                    totalLikes.textContent = parseInt(totalLikes.textContent) - 1
                    if (this.dataset.action === 'unlike'){
                        this.dataset.action = 'like'
                    }
                }
            return false
            })
        })
        {% endfor %}
    </script>
{% endblock %}

posts/templates/posts/user_posts.html
{% extends 'base.html' %}
{% load static %}

{% block extra_css %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/user_activity.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/dashboard.css' %}">
{% endblock %}
{% block text %}
    Created posts
{% endblock %}
{% block content %}
    <div class="user-links">
        <a href="{% url 'posts:user_posts' %}">
            <div class="user-link">
                Posts
                <i class="far fa-clipboard"></i>
            </div>
        </a>
        <a href="{% url 'posts:user_comments' %}">
            <div class="user-link">
                Comments
                <i class="far fa-comment"></i>
            </div>
        </a>
        <a href="{% url 'posts:user_likes' %}">
            <div class="user-link">
                Likes
                <i class="far fa-heart"></i>
            </div>
        </a>
        <a href="{% url 'posts:user_follows' %}">
            <div class="user-link">
                Follows
                <i class="fas fa-user-friends"></i>
            </div>
        </a>
    </div>

    <div class="post-list">
        {% for post in posts %}
            <div class="post-card">
                <div class="topbar">
                <a href="{{ post.user.get_absolute_url }}" class="profile-link">
                    <div class="link">
                        <div class="profile-picture">
                            <img src="{{ post.user.profile.profile_picture.url }}">
                        </div>
                        <span>{{ post.user }}</span>
                    </div>
                </a>
                     {% if request.user == post.user %}
                    <span class="delete-post">
                        <a href="#" onClick="document.getElementById('delete-form-{{ post.id }}').submit()">
                            <i class="far fa-trash-alt"></i>
                            <form method="post" action="{% url 'posts:delete_post' post.id %}" id="delete-form-{{ post.id }}">
                                {% csrf_token %}
                                <input type="hidden">
                            </form>
                        </a>
                    </span>
                {% endif %}
                </div>
                <p class="text">{{ post.text }}</p>
                <div class="under-text">
                     <span>
                            <a  data-id="{{ post.id }}"
                                data-action="{% if post in request.user.posts_liked.all %}un{% endif %}like"
                                class="like button" id="like-button-{{ post.id }}">

                                <i class="far fa-heart {% if request.user in post.users_like.all %}liked{% endif %}"
                                   id="like-icon-{{ post.id }}"></i>

                                <span class="count-total" id="like-count-{{ post.id }}">{{ post.users_like.all.count }}</span>
                            </a>
                        </span>
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    <a href="{% url 'posts:post_detail' post.slug %}" class="comment">
                        <span><i class="far fa-comment"></i></span>
                        <span class="count-total">{{ post.comments.all.count }}</span>
                    </a>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

{% block extra_js %}
    <script src="https://cdn.jsdelivr.net/npm/js-cookie@2.2.1/src/js.cookie.min.js"></script>
    <script>

        {% for post in posts %}

        document.querySelector('#like-button-{{ post.id }}').addEventListener('click', function sendPost(){
            let likeIcon = document.querySelector('#like-icon-{{ post.id }}')
            let totalLikes = document.querySelector('#like-count-{{ post.id }}')
            fetch({% url "posts:like" %}, {
                method: "POST",
                credentials: "same-origin",
                headers: {
                    "X-Requested-With": "XMLHttpRequest",
                    "X-CSRFToken": Cookies.get('csrftoken'),
                },
                body: JSON.stringify({id: this.dataset.id, action: this.dataset.action })
            })
            .then(response => response.json())
            .then(data => {
                likeIcon.classList.toggle('liked')

                if(String(data['status']) === 'liked'){
                    totalLikes.textContent = parseInt(totalLikes.textContent) + 1
                    if (this.dataset.action === 'like'){
                        this.dataset.action = 'unlike'
                    }
                } else{
                    totalLikes.textContent = parseInt(totalLikes.textContent) - 1
                    if (this.dataset.action === 'unlike'){
                        this.dataset.action = 'like'
                    }
                }
            return false
            })
        })
        {% endfor %}
    </script>
{% endblock %}